export const shipmentData = [
  {
    id: 1,
    StatusName: "About To Board",
    subtext: "Allotted for 2 Hours",
    FCL: true,
    LCL: true,
    AIR: false,
  },
  {
    id: 2,
    StatusName: "EWAY BILL RECEIVED",
    subtext: "N/A",
    FCL: true,
    LCL: false,
    AIR: true,
  },
  {
    id: 3,
    StatusName: "Arrived At Destination",
    subtext: "N/A",
    FCL: true,
    LCL: true,
    AIR: false,
  },
  {
    id: 4,
    StatusName: "Box Closing Complete",
    subtext: "N/A",
    FCL: true,
    LCL: false,
    AIR: true,
  },
  {
    id: 5,
    StatusName: "FORM 13 ISSUED",
    subtext: "Allotted for 2 Hours",
    FCL: true,
    LCL: true,
    AIR: false,
  },
  {
    id: 6,
    StatusName: "Arrived At Ts",
    subtext: "N/A",
    FCL: true,
    LCL: true,
    AIR: false,
  },
  {
    id: 7,
    StatusName: "Transhiped",
    subtext: "Alloted for 24 Hours",
    FCL: true,
    LCL: true,
    AIR: true,
  },
  {
    id: 8,
    StatusName: "Test 10",
    subtext: "N/A",
    FCL: true,
    LCL: false,
    AIR: true,
  },
];
