export const Users = [
  {
    id: 1,
    Name: "Sesha",
    Email: "sesha@123",
    Role: "Hariharan",
    Created: "N/A",
    Status: "Active",
  },
  {
    id: 2,
    Name: "Hariharan",
    Email: "hariharan@gamil.com",
    Role: "Hariharan",
    Created: "N/A",
    Status: "Active",
  },
  {
    id: 3,
    Name: "Raghu",
    Email: "Sesha",
    Role: "Hariharan",
    Created: "N/A",
    Status: "Active",
  },
  {
    id: 4,
    Name: "Punitha",
    Email: "Sesha",
    Role: "Hariharan",
    Created: "N/A",
    Status: "Active",
  },
  {
    id: 5,
    Name: "Product Design",
    Email: "Sesha",
    Role: "Hariharan",
    Created: "N/A",
    Status: "Active",
  },
];
