export const sampleData = [
  {
    customerName: "John",
    LeadDesignation: "Director",
    Email: "david@americargo.net",
    Phone: "52 3318153232",
    Mobile: "-",
    CompanySize: "Less than 50",
    City: "Guadalajara",
    Country: "Mexico",
    LeadSource: "Industry Event",
    LeadSubSource: "WCA Singapore",
    LeadType: "Freight Forwarder",
    ServicesOffered: "Sea ,Air,Inland",
    Website: "http://www.americargo.net/",
    DomainURL: "-",
    ExhibitorSponsor: "-",
    FullName: "David Ramirez",
    Company: "Americargo Logistics",
    MeetingOwner: "Raquel",
    Date: "21 Feb 2023",
    Time: "4:30:00 PM",
    LeadRegistrationID: "2238",
  },
  {
    customerName: "David",
    LeadDesignation: "Managing Director",
    Email: "gbenitez@asthoncargo.net",
    Phone: "34946612293",
    Mobile: "-",
    CompanySize: "Less than 50",
    City: "Valencia",
    Country: "Spain",
    LeadSource: "Industry Event",
    LeadSubSource: "WCA Singapore",
    LeadType: "NVOCC",
    ServicesOffered: "Sea,Air,Inland,FCL,LCL",
    Website: "http://www.asthoncargo.es/web/",
    DomainURL: "-",
    ExhibitorSponsor: "-",
    FullName: "Gustavo Benitez",
    Company: "Asthon Cargo",
    MeetingOwner: "Raquel",
    Date: "22 Feb 2023",
    Time: "11:00:00 AM",
    LeadRegistrationID: "1347",
  },
  {
    customerName: "Jonathan",
    LeadDesignation: "Director",
    Email: "LJUL22@EMAIL.COM",
    Phone: "917 971-5007",
    Mobile: "-",
    CompanySize: "-",
    City: "New York",
    Country: "United States of America",
    LeadSource: "Industry Event",
    LeadSubSource: "WCA Singapore",
    LeadType: "NVOCC",
    ServicesOffered: "Sea,Air,Inland.",
    Website: "http://airfleetlogistics.com/",
    DomainURL: "-",
    ExhibitorSponsor: "-",
    FullName: "David Ramirez",
    Company: "Americargo Logistics",
    MeetingOwner: "Raquel",
    Date: "21 Feb 2023",
    Time: "10:30:00 AM",
    LeadRegistrationID: "3135",
  },
  {
    customerName: "Tommy",
    LeadDesignation: "General Manager",
    Email: "virginia@vicentebadenes.com",
    Phone: "34963671394",
    Mobile: "-",
    CompanySize: "Less than 50",
    City: "Valencia",
    Country: "Spain",
    LeadSource: "Industry Event",
    LeadSubSource: "WCA Singapore",
    LeadType: "NVOCC",
    ServicesOffered: "Sea ,Air,Inland",
    Website: "https://vicentebadenes.com/en/",
    DomainURL: "-",
    ExhibitorSponsor: "-",
    FullName: "Virginia Badenes",
    Company: "Badenes Logistics",
    MeetingOwner: "Raquel",
    Date: "21 Feb 2023",
    Time: "2:00:00 PM",
    LeadRegistrationID: "3238",
  },
  {
    customerName: "George",
    LeadDesignation: "Managing Director",
    Email: "csantisteban@bosscontinental.com",
    Phone: "34 914900112",
    Mobile: "-",
    CompanySize: "Less than 50",
    City: "Madrid",
    Country: "Spain",
    LeadSource: "Industry Event",
    LeadSubSource: "WCA Singapore",
    LeadType: "NVOCC",
    ServicesOffered: "Sea ,Air,Inland",
    Website: "https://bosscontinental.com/",
    DomainURL: "-",
    ExhibitorSponsor: "-",
    FullName: "Cristina Perez",
    Company: "Boss Continental",
    MeetingOwner: "Raquel",
    Date: "21 Feb 2023",
    Time: "11:30:00 AM",
    LeadRegistrationID: "2257",
  },
  {
    customerName: "William",
    LeadDesignation: "GM Operations",
    Email: "dean.bell@btl.com.au",
    Phone: "61 2 9540 6411 / 61 2 9540 6400",
    Mobile: "-",
    CompanySize: "50 to 500",
    City: "Sydney",
    Country: "Australia",
    LeadSource: "Industry Event",
    LeadSubSource: "WCA Singapore",
    LeadType: "NVOCC",
    ServicesOffered: "Sea ,Air,Inland",
    Website: "www.btl.com.au",
    DomainURL: "@btl.com.au",
    ExhibitorSponsor: "-",
    FullName: "Dean Bell",
    Company: "Bell Total Logistics Pty Ltd",
    MeetingOwner: "Bala",
    Date: "21 Feb 2023",
    Time: "1:30:00 PM",
    LeadRegistrationID: "811",
  },
  {
    customerName: "Harry",
    LeadDesignation: "Pricing Coordinator",
    Email: "rodrigues@carpolog.com.br",
    Phone: "55 1321047000",
    Mobile: "-",
    CompanySize: "50 to 500",
    City: "Santos",
    Country: "Brazil",
    LeadSource: "Industry Event",
    LeadSubSource: "WCA Singapore",
    LeadType: "NVOCC",
    ServicesOffered: "Sea ,Air,Inland",
    Website: "https://www.carpolog.com.br/",
    DomainURL: "-",
    ExhibitorSponsor: "-",
    FullName: "Thais Rodrigues",
    Company: "Carpo Logistics",
    MeetingOwner: "Raquel",
    Date: "22 Feb 2023",
    Time: "4:00:00 PM",
    LeadRegistrationID: "1248",
  },
  {
    customerName: "Paul Heyman",
    LeadDesignation: "Operations Supervisor",
    Email: "LJUL22@EMAIL.COM",
    Phone: "61 3 9369 3319",
    Mobile: "-",
    CompanySize: "Less than 50",
    City: "Melbourne",
    Country: "Australia",
    LeadSource: "Industry Event",
    LeadSubSource: "WCA Singapore",
    LeadType: "NVOCC",
    ServicesOffered: "Sea ,Air,Inland",
    Website: "www.dlf.net.au",
    DomainURL: "@dlf.net.au",
    ExhibitorSponsor: "-",
    FullName: "Chantanat Pepper Yowa",
    Company: "DLF Global Logistics Pty Ltd",
    MeetingOwner: "Bala",
    Date: "21 Feb 2023",
    Time: "4:30:00 PM",
    LeadRegistrationID: "1248",
  },
  {
    customerName: "Jack",
    LeadDesignation: "CEO",
    Email: "LJUL22@EMAIL.COM",
    Phone: "32 02 751 50 45",
    Mobile: "-",
    CompanySize: "Less than 50",
    City: "Brussels",
    Country: "Belgium",
    LeadSource: "Industry Event",
    LeadSubSource: "WCA Singapore",
    LeadType: "Freight Forwarder",
    ServicesOffered: "Sea ,Air,Inland",
    Website: "www.eagleair.be",
    DomainURL: "@eagleair.be",
    ExhibitorSponsor: "Exhibitor",
    FullName: "Axel De Greef",
    Company: "Eagle Air Agencies",
    MeetingOwner: "Jesper",
    Date: "22 Feb 2023",
    Time: "11:00:00 AM",
    LeadRegistrationID: "1232",
  },
  {
    customerName: "Jack",
    LeadDesignation: "General Manager",
    Email: "mikel@intermodalforwarding.com",
    Phone: "34944939200",
    Mobile: "-",
    CompanySize: "Less than 50",
    City: "Bilbao",
    Country: "Spain",
    LeadSource: "Industry Event",
    LeadSubSource: "WCA Singapore",
    LeadType: "Freight Forwarder",
    ServicesOffered: "Sea ,Air,Inland",
    Website: "https://intermodalforwarding.com/",
    DomainURL: "@eagleair.be",
    ExhibitorSponsor: "Exhibitor",
    FullName: "Mikel Lavin",
    Company: "Intermodal Forwarding",
    MeetingOwner: "Bala",
    Date: "20 Feb 2023",
    Time: "2:00:00 PM",
    LeadRegistrationID: "1901",
  },
];
